# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_task_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='yo',
            field=models.CharField(default=True, max_length=128, null=True),
        ),
    ]
