# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 06:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_task_yo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='yo',
        ),
    ]
