# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_remove_task_yo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_posted',
            field=models.DateTimeField(null=True),
        ),
    ]
