# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 03:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_auto_20170812_0812'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserJob',
            new_name='UserTask',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='owner',
        ),
    ]
