# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 03:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_auto_20170814_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertask',
            old_name='user',
            new_name='profile',
        ),
    ]
