# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_auto_20170814_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='question1_answer',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='usertask',
            name='question2_answer',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='usertask',
            name='question3_answer',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
