# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_auto_20170819_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('SL', 'Shortlisted'), ('AP', 'Applied'), ('AS', 'Assigned'), ('C', 'Complete'), ('D', 'Discarded'), ('R', 'Rejected')], default='O', max_length=2),
        ),
    ]
