# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0021_auto_20170819_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
