# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0023_auto_20170822_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiletask',
            name='status',
            field=models.CharField(choices=[('SL', 'Shortlisted'), ('AP', 'Applied'), ('D', 'Discarded'), ('R', 'Rejected')], default='SL', max_length=2),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('IC', 'Incomplete'), ('IP', 'In Progress'), ('C', 'Complete')], default='IC', max_length=2),
        ),
    ]
