# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0023_auto_20170822_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='Hugo', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='Edwards', max_length=128),
            preserve_default=False,
        ),
    ]
