# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 06:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0024_auto_20170906_1543'),
        ('jobs', '0024_auto_20170906_1517'),
    ]

    operations = [
    ]
