# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 06:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0025_merge_20170906_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='helper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='helper', to='jobs.Profile'),
        ),
        migrations.AlterField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poster', to='jobs.Profile'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('I', 'In Progress'), ('C', 'Complete')], default='O', max_length=2),
        ),
    ]
