# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0027_auto_20170906_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_remote',
            field=models.BooleanField(default=False),
        ),
    ]
