# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 00:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0029_auto_20170907_1256'),
        ('jobs', '0028_task_is_remote'),
    ]

    operations = [
    ]
