# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 00:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0032_auto_20170908_1404'),
        ('jobs', '0031_auto_20170908_1713'),
    ]

    operations = [
    ]
