# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0033_merge_20170909_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='DELETEME.jpg', upload_to='%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
