# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0034_auto_20170909_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiletask',
            name='quote',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
