# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0035_profiletask_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='skills',
            field=models.ManyToManyField(to='jobs.Skill'),
        ),
    ]
