# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0036_task_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='code',
            field=models.CharField(default='doggo', max_length=20),
            preserve_default=False,
        ),
    ]
