# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 08:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0033_auto_20170908_1704'),
        ('jobs', '0037_skill_code'),
    ]

    operations = [
    ]
