# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0040_task_display_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileskill',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
