# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 03:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0041_auto_20170917_1250'),
        ('jobs', '0040_profiletask_rating'),
    ]

    operations = [
    ]
