# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0043_auto_20170918_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='skills',
            field=models.ManyToManyField(null=True, to='jobs.Skill'),
        ),
    ]
