# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 22:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0046_remove_task_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='description',
        ),
    ]
