# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0049_profile_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiletask',
            name='rating',
            field=models.IntegerField(blank=True, default=0.0),
        ),
    ]
