# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0050_auto_20170926_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='profiletask',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
