# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 06:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0054_profile_shortlists'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='points',
            new_name='offer',
        ),
    ]
