# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0055_auto_20171004_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tasks_completed',
            field=models.IntegerField(default=0),
        ),
    ]
