# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-08 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0056_profile_tasks_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_due',
            field=models.DateField(blank=True, null=True),
        ),
    ]
