# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0057_task_date_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiletask',
            name='datetime_applied',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
